---
kind: pipeline
type: kubernetes
name: build

trigger:
  branch:
  - main
  - develop
  - feature/*
  event:
  - push
  #paths:
  #  exclude:
  #  - README.md

steps:
- name: hello, world
  image: golang:1.15.2-alpine3.12
  commands:
  - echo "Hello, World"
  when:
    branch:
    - main
    - develop
    - feature/*
    paths:
      exclude:
      - README.md
